# Script used by CI tool codecov.io

codecov:
  ci:
    - "travis.org"

coverage:
  precision: 1
  round: down
  # The value range where the value to be green
  range: "80...100"

  status:
    project:
      default:
        # For project code, the target is set at 60% +- 5% coverage
        target: 60
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        # For new changes, the target is set at 80% coverage
        target: 80
        threshold: 0%
        if_ci_failed: error